// Smart Transliteration & Hindi Voice Formatter for Native Human TTS

const HINGLISH_TO_DEVANAGARI_WORDS: Record<string, string> = {
  // Common sentence phrases
  aapki: 'आपकी',
  aapka: 'आपका',
  list: 'लिस्ट',
  cart: 'कार्ट',
  mein: 'में',
  se: 'से',
  jod: 'जोड़',
  diya: 'दिया',
  gaya: 'गया',
  gaye: 'गए',
  hai: 'है',
  hain: 'हैं',
  hata: 'हटा',
  kam: 'कम',
  kar: 'कर',
  diye: 'दिए',
  bache: 'बचे',
  aur: 'और',
  batao: 'बताओ',
  chahiye: 'चाहिए',
  samaan: 'सामान',
  saare: 'सारे',
  saara: 'सारा',
  items: 'आइटम्स',
  item: 'आइटम',
  khali: 'खाली',
  total: 'टोटल',
  lagbhag: 'लगभग',
  pichla: 'पिछला',
  action: 'एक्शन',
  wapas: 'वापस',
  le: 'ले',
  liya: 'लिया',
  tick: 'टिक',
  mark: 'मार्क',
  done: 'डन',
  abhi: 'अभी',
  pehle: 'पहले',
  hi: 'ही',
  nahi: 'नहीं',
  mila: 'मिला',
  kuch: 'कुछ',
  bhi: 'भी',
  badhiya: 'बढ़िया',
  hoon: 'हूँ',
  madad: 'मदद',
  karne: 'करने',
  ke: 'के',
  liye: 'लिए',
  tayar: 'तैयार',
  aaj: 'आज',
  kya: 'क्या',
  karna: 'करना',
  shukriya: 'शुक्रिया',
  tareef: 'तारीफ',
  pasandeeda: 'पसंदीदा',
  alvida: 'अलविदा',
  jab: 'जब',
  bas: 'बस',
  mic: 'माइक',
  dabaiye: 'दबाइए',
  main: 'मैं',
  bilkul: 'बिल्कुल',
  zaroor: 'ज़रूर',
  dhanyawad: 'धन्यवाद',
  namaste: 'नमस्ते',

  // Units & Numbers
  pack: 'पैक',
  packets: 'पैकेट',
  packet: 'पैकेट',
  kg: 'किलो',
  kilo: 'किलो',
  litre: 'लीटर',
  litres: 'लीटर',
  liter: 'लीटर',
  gram: 'ग्राम',
  gm: 'ग्राम',
  pcs: 'पीस',
  piece: 'पीस',
  bottle: 'बोतल',
  box: 'डिब्बा',
  ek: '1',
  do: '2',
  teen: '3',
  char: '4',
  paanch: '5',
  chhe: '6',
  saat: '7',
  aath: '8',
  nau: '9',
  dus: '10',

  // Common Produce
  tamatar: 'टमाटर',
  tomato: 'टमाटर',
  tomatoes: 'टमाटर',
  aloo: 'आलू',
  potato: 'आलू',
  potatoes: 'आलू',
  pyaz: 'प्याज',
  onion: 'प्याज',
  onions: 'प्याज',
  seb: 'सेब',
  apple: 'सेब',
  apples: 'सेब',
  kela: 'केला',
  kele: 'केले',
  banana: 'केला',
  bananas: 'केले',
  aam: 'आम',
  mango: 'आम',
  mangoes: 'आम',
  doodh: 'दूध',
  dudh: 'दूध',
  milk: 'दूध',
  makkhan: 'मक्खन',
  makhan: 'मक्खन',
  butter: 'मक्खन',
  paneer: 'पनीर',
  dahi: 'दही',
  curd: 'दही',
  atta: 'आटा',
  namak: 'नमक',
  salt: 'नमक',
  cheeni: 'चीनी',
  sugar: 'चीनी',
  chai: 'चाय',
  tea: 'चाय',
  tel: 'तेल',
  oil: 'तेल',
  chawal: 'चावल',
  rice: 'चावल',
  dal: 'दाल',
  ande: 'अंडे',
  anda: 'अंडा',
  eggs: 'अंडे',
  egg: 'अंडा',
  nimbu: 'नींबू',
  lemon: 'नींबू',
  dhaniya: 'धनिया',
  adrak: 'अदरक',
  lahsun: 'लहसुन',
  mirchi: 'मिर्ची',
  palak: 'पालक',
  gobi: 'गोभी',
  matar: 'मटर',
  gajar: 'गाजर',
  kheera: 'खीरा',
  bhindi: 'भिंडी',
  maggi: 'मैगी',
  biscuit: 'बिस्किट',
  biscuits: 'बिस्किट',
}

/**
 * Converts Hinglish romanized sentences to clean Devanagari text
 * for native speech synthesis engines to speak with 100% human fluency.
 */
export function formatHindiForTTS(text: string): string {
  if (!text) return ''

  // Preserve currency and punctuation
  const clean = text.replace(/₹/g, 'रुपये ')

  const tokens = clean.split(/(\s+|[.,!?()])/g)
  const converted = tokens.map((token) => {
    const lower = token.toLowerCase().trim()
    if (HINGLISH_TO_DEVANAGARI_WORDS[lower]) {
      return HINGLISH_TO_DEVANAGARI_WORDS[lower]
    }
    return token
  })

  return converted.join('')
}
